# Generated by Django 5.2 on 2025-09-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothing', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
